
language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell
        - chmod +x {TRAVIS_BUILD_DIR}/tests/run.ps1
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell

script:
  - pwsh -C Install-Module Pester -Force -Scope CurrentUser -SkipPublisherCheck; ${TRAVIS_BUILD_DIR}/tests/run.ps1

after_script:
  - pwsh -C Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
  - pwsh -C ./codecov.sh -f ${TRAVIS_BUILD_DIR}/tests/CodeCoverage.xml