
image:
- Visual Studio 2017
- Ubuntu

build: off

install:
  - ps: Install-Module Pester -Force -Scope CurrentUser -SkipPublisherCheck

test_script:
  - ps: .\tests\run.ps1

after_test:
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile ./codecov.sh
  - ps: ./codecov.sh -f ./tests/CodeCoverage.xml