
image:
- Visual Studio 2017

build: off

test_script:
  - ps: ${$Env:APPVEYOR_BUILD_FOLDER}\\ci\\Build.ps1 -Ci:(${$Env:APPVEYOR_REPO_COMMIT_MESSAGE} -NotContains [SkipCi]) -BuildId ${$Env:APPVEYOR_BUILD_ID}